# Generated by Django 5.1.3 on 2024-11-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_benne_camion_client_fourniseur_operrateur_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operrateur',
            name='id_operateur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
