# Generated by Django 5.1.3 on 2024-11-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_operrateur_id_operateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='id_option',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
