# Generated by Django 5.1.3 on 2024-11-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_option_id_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='benne',
            name='id_benne',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
