# Generated by Django 5.1.3 on 2024-11-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_benne_id_benne'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='id_camion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
