# Generated by Django 5.1.3 on 2024-11-19 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_camion_id_camion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontagePossible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_montage', models.CharField(blank=True, max_length=100, null=True)),
                ('allonge_chassis', models.BooleanField(default=True)),
                ('surelevation', models.BooleanField(default=True)),
                ('espacement_cabine', models.CharField(max_length=50)),
                ('benne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.benne')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.camion')),
            ],
        ),
    ]
