# Generated by Django 5.1.3 on 2024-11-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_montagepossible_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benne',
            old_name='tps_peinture_reel',
            new_name='tps_peinture_standard',
        ),
        migrations.AlterField(
            model_name='montagepossible',
            name='id_auto_montage',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
