# Generated by Django 5.1.3 on 2024-11-25 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_rename_tps_peinture_reel_benne_tps_peinture_standard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tps_travail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tps_option_reel', models.FloatField()),
                ('tps_montage_reel', models.FloatField()),
                ('tps_peinture_reel', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CalculEcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.benne')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.option')),
                ('tps_travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.tps_travail')),
            ],
        ),
    ]
