# Generated by Django 5.1.3 on 2024-11-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_tps_travail_calculecart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tps_travail',
            name='tps_montage_reel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='tps_option_reel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='tps_peinture_reel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
