# Generated by Django 5.1.3 on 2024-11-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_tps_travail_tps_montage_reel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps_travail',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.commande'),
        ),
        migrations.AddField(
            model_name='tps_travail',
            name='operateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.operrateur'),
        ),
    ]
