# Generated by Django 5.1.3 on 2024-12-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_tps_travail_commande_tps_travail_operateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='temps_actuel',
        ),
    ]
