# Generated by Django 5.1.3 on 2024-12-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_remove_commande_temps_actuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='official_homepage',
        ),
    ]
