# Generated by Django 5.1.3 on 2024-12-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_remove_band_official_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='benne',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='camion',
        ),
        migrations.AddField(
            model_name='commande',
            name='MontagePossible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.montagepossible'),
        ),
    ]
