# Generated by Django 5.1.4 on 2024-12-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_remove_commande_benne_remove_commande_camion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='band',
        ),
        migrations.RemoveField(
            model_name='calculecart',
            name='benne',
        ),
        migrations.RemoveField(
            model_name='calculecart',
            name='option',
        ),
        migrations.RemoveField(
            model_name='calculecart',
            name='tps_travail',
        ),
        migrations.DeleteModel(
            name='Fourniseur',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='CalculEcart',
        ),
    ]
