# Generated by Django 5.1.4 on 2024-12-27 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_remove_listing_band_remove_calculecart_benne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps_travail',
            name='tps_montage_standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='montage_standards', to='listings.benne'),
        ),
        migrations.AddField(
            model_name='tps_travail',
            name='tps_option_standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='option_standards', to='listings.option'),
        ),
        migrations.AddField(
            model_name='tps_travail',
            name='tps_peinture_standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='peinture_standards', to='listings.benne'),
        ),
    ]
