# Generated by Django 5.1.4 on 2024-12-27 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_tps_travail_tps_montage_standard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tps_travail',
            name='operateur',
        ),
        migrations.AddField(
            model_name='tps_travail',
            name='operateur_principal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tps_principal', to='listings.operrateur'),
        ),
        migrations.AddField(
            model_name='tps_travail',
            name='operateur_secondaire',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tps_secondaire', to='listings.operrateur'),
        ),
    ]
