# Generated by Django 5.1.4 on 2024-12-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_remove_tps_travail_operateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps_travail',
            name='operateur_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tps_operateur_2', to='listings.operrateur'),
        ),
        migrations.AddField(
            model_name='tps_travail',
            name='operateur_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tps_operateur_3', to='listings.operrateur'),
        ),
    ]
