# Generated by Django 5.1.4 on 2024-12-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_tps_travail_operateur_2_tps_travail_operateur_3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operrateur',
            new_name='Operateur',
        ),
    ]
