# Generated by Django 5.1.4 on 2024-12-27 22:12

import django.db.models.deletion
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_rename_operrateur_operateur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tps_travail',
            options={'ordering': ['commande'], 'verbose_name': 'Temps de Travail', 'verbose_name_plural': 'Temps de Travail'},
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.commande', verbose_name='Commande associée'),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='operateur_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tps_travail_operateur_2', to='listings.operateur'),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='operateur_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tps_travail_operateur_3', to='listings.operateur'),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='operateur_principal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tps_travail_principal', to='listings.operateur'),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='operateur_secondaire',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tps_travail_secondaire', to='listings.operateur'),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='tps_montage_reel',
            field=models.FloatField(blank=True, null=True, validators=[listings.models.validate_positive], verbose_name='Temps Montage Réel'),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='tps_option_reel',
            field=models.FloatField(blank=True, null=True, validators=[listings.models.validate_positive], verbose_name='Temps Option Réel'),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='tps_peinture_reel',
            field=models.FloatField(blank=True, null=True, validators=[listings.models.validate_positive], verbose_name='Temps Peinture Réel'),
        ),
    ]
