# Generated by Django 5.1.4 on 2024-12-27 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_alter_tps_travail_options_alter_tps_travail_commande_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tps_travail',
            options={},
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.commande'),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='operateur_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tps_operateur_2', to='listings.operateur'),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='operateur_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tps_operateur_3', to='listings.operateur'),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='operateur_principal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tps_principal', to='listings.operateur'),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='operateur_secondaire',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tps_secondaire', to='listings.operateur'),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='tps_montage_reel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='tps_option_reel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tps_travail',
            name='tps_peinture_reel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
